name: emgu-actions
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Dotnet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Emgu Docker Sample
        run: sh ./build_docker
