name: emgu-actions
on: [push]
jobs:
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [linux]
        include: 
          - target: linux
            os: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Dotnet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.5.21302.13'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker for Dev (develop only)
        if: github.ref == 'refs/heads/develop'
        run: sh publish.sh
